CREATE TABLE `trade` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(30) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci` NOT NULL,
  `type` VARCHAR(30) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci` NOT NULL,
  `buyQuantity` DOUBLE,
  `sellQuantity` DOUBLE,
  `buyPrice` DOUBLE,
  `sellPrice` DOUBLE,
  `tradeDate` DATETIME,
  `security` VARCHAR(125) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`,
  `status` VARCHAR(10) CHARACTER SET `ascii` COLLATE `ascii_bin`,
  `trader` VARCHAR(125) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`,
  `benchmark` VARCHAR(125) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`,
  `book` VARCHAR(125) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`,
  `creationName` VARCHAR(125) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`,
  `creationDate` DATETIME NOT NULL DEFAULT current_timestamp(),
  `revisionName` VARCHAR(125) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`,
  `revisionDate` DATETIME,
  `dealName` VARCHAR(125) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`,
  `dealType` VARCHAR(125) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`,
  `sourceListId` VARCHAR(125) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`,
  `side` VARCHAR(125) CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_ci`,

  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = `utf8mb4` ROW_FORMAT = COMPACT;
