CREATE TABLE `rating` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `moodysRating` VARCHAR(125) CHARACTER SET `ascii` COLLATE `ascii_bin` NOT NULL,
  `sandPRating` VARCHAR(125) CHARACTER SET `ascii` COLLATE `ascii_bin` NOT NULL,
  `fitchRating` VARCHAR(125) CHARACTER SET `ascii` COLLATE `ascii_bin` NOT NULL,
  `orderNumber` TINYINT NOT NULL DEFAULT 0,

  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = `utf8mb4` ROW_FORMAT = COMPACT;
